### PR TITLE
First draft of community documentation template

### PR DESCRIPTION
**Pull request by gusferguson**
@jburel @hflynn 

For review and comment.

### CODE REVIEW

**Comment by jburel** [comment]
@gusferguson: do you have commits to push?

**Comment by gusferguson** [comment]
@jburel  - I just have the template file in this PR.

**Comment by jburel** [comment]
you have 2 characters that need to be fixed i.e. `Developer�s`

**Comment by jburel** [comment]
`self-explanatory:` should be `.`

**Comment by jburel** [comment]
`Critical Requirements` is it under that section that people will describe the setup plan: e.g. omero running on centos7, analysis on cluster, file storage: samba share, use of in-place import due to size of  data.

I will rename Critical by essentials: we may also want to have an example on each key section

**Comment by jburel** [comment]
Thanks @gusferguson we can also improve it following feedback we receive.

**Pull request merged**
